# .rubocop.yml

Style/Documentation:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/EndOfLine: # Rubocop doesn't like the "frozen_string_literal: true" that it automatically adds
  Exclude:
    - "**/**/*"

Naming/ClassAndModuleCamelCase:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 50

AllCops:
  Exclude:
    - "spec/**/*"
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "bin/{rails,rake}"
    - !ruby/regexp /old_and_unusued\.rb$/
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/bundle"
    - "node_modules/**/*"
    - "Gemfile"
